language: go
os: linux
dist: bionic

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
