language: go
os: linux
dist: bionic

jobs:
  include:
    - go: 1.11.x
      env: GO111MODULE=on
    - go: 1.12.x
      env: GO111MODULE=on
    - go: 1.13.x
    - go: 1.14.x
    - go: master

install:
  - go mod download

script:
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
